### ISSUE TITLE
--keep-missed switch should default to TRUE

### ISSUE THREAD

**Issue by maestr0** [haftahave/serverless-ses-template#1]
--keep-missed switch should default to **true** 

It's totally not safe to assume that all the email templates which are not in this plugin configuration can be deleted. You can have multiple other templates from different projects uploaded with different tools and this plugin will just delete them without a warning. 

I would completely remove this feature or if you want to keep it, add a project-specific prefix to each template so you would only remove templates with that prefix.

**Comment by Enase** [comment]
Totally agree, will fix it soon. thanks for your feedback
