### ISSUE TITLE
Request: Do not add alias to template name if alias plugin unused

### ISSUE THREAD

**Issue by mcous** [haftahave/serverless-ses-template#10]
Hi, thanks for your hard work on this plugin! I'm hoping it will be useful in a project I'm working on.

To be able to use this plugin, though, I have a request: my project doesn't use the `serverless-aws-alias` plugin, but I _do_ want my templates named by stage. Rather than default the alias suffix to `production` if the `sesTemplatesAddStageAlias` option is set to `true`, I think a sensible default for this plugin would be to omit the alias suffix entirely if no alias configuration is found.

Would you accept a PR for this functionality?

**Comment by Enase** [comment]
Hi @mcous. Sure, feel free to create PR.
