### ISSUE TITLE
Async support ?

### ISSUE THREAD

**Issue by robertsonsamuel** [haftahave/serverless-ses-template#15]
Any idea if there is a way to build in support for async operations? I would love to be able to fetch the templates from a database or API call before.

**Comment by Enase** [comment]
@robertsonsamuel I hope I understand you correct and you want to have a way to load template configuration from database or any other "async" source. Yes, It's good idea. Would be great if you will describe your implementation proposal in details (if you have any of course). I think I will add next release, but I don't have ETA for it.

**Comment by Enase** [comment]
Ability to load template configuration in any async way add.
Thanks for your suggestion, feel free to use version [1.3.0](https://github.com/haftahave/serverless-ses-template/releases/tag/1.3.0).
