### ISSUE TITLE
Don't sync plugins on `package` command?

### ISSUE THREAD

**Issue by vladgolubev** [haftahave/serverless-ses-template#16]
Hey there, thanks for the plugin BTW!

Is there a reason this plugin deploys templates during the `package` stage and not before the `deploy` stage?

This presents a problem for us, since we run `serverless package` many times during development to produce artifact and compiled serverless cloudformation template and then run `serverless deploy` once after PR is reviewed.

Is there a way to change this to run on `deploy` stage?

**Comment by Enase** [comment]
Good suggestion, I'll try to think of a better way to do it. Also, feel free to PR or share your other ideas.
Hope to start/finish it this week.

**Comment by Enase** [comment]
@vladgolubev SES template deploy process moved from "packaging" to "before deploy" stage.
Thanks for your suggestion, feel free to use version [1.3.2](https://github.com/haftahave/serverless-ses-template/blob/master/CHANGELOG.md).

**Comment by vladgolubev** [comment]
Awesome! Thanks for such a quick resolution, Sergii!
