### ISSUE TITLE
Does not seem to update templates with <!--[if (!mso)>, and similar tags

### ISSUE THREAD

**Issue by talaikis** [haftahave/serverless-ses-template#27]
Latest version works fine with pure HTML templates, but any changes to the <!--[if (!mso)> part are omitted. Probably aws-sdk problem, will try to reproduce.

**Comment by Enase** [comment]
Hi @talaikis. Could you give any example? Thanks.

**Comment by talaikis** [comment]
Trying to reproduce it. Small reproduction package works fine, when exact same thing does not update templates for a project with a lot of functions.

**Comment by talaikis** [comment]
Ok, here's the problem. I have deleted existing templates and after redeployed the stack realized that none of the templates are recreated (no errors, usual log). Why is so hard to say as working repro and the non-working stack have same versions, except that one is much older than another.
