### ISSUE TITLE
Template upload does not work

### ISSUE THREAD

**Issue by skrosoft** [haftahave/serverless-ses-template#5]
The plugin says everything is ok:

```
Serverless: AWS SES template synchronization start
Serverless: Going to create template "example_name_dev_production"
Serverless: AWS SES template synchronization complete
```

But the tempalte doesn't appear on SES dashboard and this error appear when trying to send the email:

` { TemplateDoesNotExist: Template example_name_dev_production does not exist ... `

@Enase  Can you observe this problem?

**Comment by Enase** [comment]
Hi @skrosoft.

I recommend you to trace your template configuration and `SES.createTemplate`.
You can find it [here](https://github.com/haftahave/serverless-ses-template/blob/master/index.js#L262].
Try it like:
```
        const params = {
            Template: {
                TemplateName: this.addStageAliasToTemplateName(name),
                SubjectPart: subject,
                HtmlPart: html,
                TextPart: text,
            },
        };
        console.log('Template params=', params);
        this.serverless.cli.log(`Going to create template "${templateName}"`);
        return this.provider.request('SES', 'createTemplate', params).then((result) => {
              console.log(`Template "${templateName}" created, result=`, result)
        });
```
Thanks,
Sergii

**Comment by Enase** [comment]
Hi @skrosoft!
Issue found and fixed.
Feel free to use new version [1.0.6](https://github.com/haftahave/serverless-ses-template/releases/tag/1.0.6).
Thanks.
