### ISSUE TITLE
custom key to configure the SES region in serverless.yml

### ISSUE THREAD

**Issue by fusionbeam** [haftahave/serverless-ses-template#8]
When dealing with complex services with resources scattered across multiple regions one needs to be able to define a particular region that supports SES templates.
This region may be different than the profile region.
A way to address this would be through a custom key such as 'sesTemplatesRegion'. Its value could be used if no region is specified in the command line.

**Comment by Enase** [comment]
@fusionbeam nice idea, will do it soon.

**Comment by fusionbeam** [comment]
Great! In the same spirit the 'region' command line parameter overlaps with other plugins.

My suggestion is to use the following fallback sequence to set the region for the ses-template plugin

param 'sesTemplatesRegion' -otherwise- customKey 'sesTemplatesRegion'  -otherwise-  param 'region' -otherwise- profile 'region'

**Comment by Enase** [comment]
@fusionbeam finally I did it.
See details in pull request https://github.com/haftahave/serverless-ses-template/pull/9
Take into account that it has breaking changes and feel free to use new updated version.
Thanks for your suggestion.

**Comment by fusionbeam** [comment]
thank you for your effort. will test shortly.
